# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
r: bioc-devel
bioc_packages: BiocCheck
# in order to sync with devtools::check()
#r_check_args: --as-cran --timings --no-manual
warnings_are_errors: true
# customize build to add biocCheck? (not tested)
script:
    - R CMD build . --no-resave-data --no-manual
    - R CMD check *tar.gz --as-cran --timings --no-manual
    - R CMD BiocCheck icetea_0.98.0.tar.gz
os:
    - linux
    - osx
